version: "3.9"

services:
  frontend:
    image: hayden1233/crop_vite_react:latest
    container_name: crop-frontend
    expose:
      - 80
    restart: unless-stopped

  spring:
    image: hayden1233/crop-spring:latest
    container_name: spring-app
    expose:
      - "8080"

  fastapi:
    image: hayden1233/crop-fastapi:latest
    container_name: fastapi-app
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:      
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - react
      - spring
      - fastapi
    restart: unless-stopped
